version: "3"

services:
  app:
    container_name: assesment_api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - config=.env-prod
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
  postgres:
    container_name: postgres
    image: 'postgres:12'
    ports:
      - '8001:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env-prod 
  redis-server:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
volumes:
  db:
    driver: local